'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,CheckCircle2,Coins,Gamepad2,Info,ShoppingBag,Sparkles} from 'lucide-react';
import GreenShell from '@/app/components/GreenShell';
import {useStudent} from '@/app/lib/useStudent';
import {supabase} from '@/lib/supabaseClient';
type Item={id:string;name:string;price:number;icon:string;category:string};type Plot={slot:number;item_id:string};
export default function Garden(){const {userId}=useStudent();const [credits,setCredits]=useState(0),[items,setItems]=useState<Item[]>([]),[plots,setPlots]=useState<Plot[]>([]),[chosen,setChosen]=useState<Item|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState<'garden'|'store'>('garden');
 async function load(){if(!userId)return;const [w,i,g]=await Promise.all([supabase.from('gf_wallets').select('credits').eq('user_id',userId).maybeSingle(),supabase.from('gf_items').select('id,name,price,icon,category').eq('active',true).order('price'),supabase.from('gf_garden').select('slot,item_id').eq('user_id',userId)]);setCredits(Number(w.data?.credits)||0);setItems((i.data||[]) as Item[]);setPlots((g.data||[]) as Plot[])}
 useEffect(()=>{void load()},[userId]);
 async function place(slot:number){if(!chosen||busy)return;setBusy(true);setError('');setMessage('');const {error}=await supabase.rpc('gf_purchase_item',{p_item:chosen.id,p_slot:slot});if(error)setError(error.message);else{setMessage(`${chosen.name} added to your world!`);setChosen(null);await load()}setBusy(false)}
 return <GreenShell><div className="gf-screen gf-v3-page gf-v3-garden">
   <header className="gf-v3-page-heading"><span className="gf-v3-eyebrow">YOUR CREATIVE CORNER</span><h1>My Green World<span className="gf-v3-title-period">.</span></h1><p>Earn Green Credits through real actions. Build a little world of your own.</p></header>
   <div className="gf-v3-world-scene"><div className="gf-v3-world-sun"/><div className="gf-v3-world-cloud cloud-1"/><div className="gf-v3-world-cloud cloud-2"/><div className="gf-v3-world-hill hill-back"/><div className="gf-v3-world-hill hill-front"/><div className="gf-v3-world-tree tree-one"><span/></div><div className="gf-v3-world-tree tree-two"><span/></div><div className="gf-v3-world-house"><span className="roof"/><span className="walls"/><span className="door"/></div><span className="gf-v3-world-caption"><Sparkles size={16}/> Your world, your pace</span></div>
   <div className="gf-v3-world-stats"><div><small>Green Credits</small><strong><Coins size={19}/>{credits.toLocaleString()}</strong></div><div><small>Items placed</small><strong>{plots.length} <span>/ 12</span></strong></div><div><small>Open spaces</small><strong>{Math.max(0,12-plots.length)}</strong></div></div>
   <div className="gf-v3-segment gf-v3-world-tabs" role="group" aria-label="Garden or shop"><button className={tab==='garden'?'selected':''} type="button" onClick={()=>setTab('garden')} aria-pressed={tab==='garden'}><Gamepad2 size={17}/> My Garden</button><button className={tab==='store'?'selected':''} type="button" onClick={()=>setTab('store')} aria-pressed={tab==='store'}><ShoppingBag size={17}/> Store</button></div>
   {error&&<p className="gf-error" role="alert">{error}</p>}{message&&<p className="gf-success" role="status"><CheckCircle2 size={16}/> {message}</p>}
   {tab==='garden'?<section className="gf-v3-world-content"><div className="gf-v3-section-heading"><div><span className="gf-v3-eyebrow">YOUR LAND</span><h2>Make it your own</h2></div><button type="button" onClick={()=>setTab('store')} className="gf-v3-world-link">Explore store <ArrowRight size={15}/></button></div><p className="gf-v3-world-subtitle">{chosen?`Select an empty space to place ${chosen.name} for ${chosen.price} credits.`:'Pick an item from the store and choose an empty spot to place it.'}</p><div className="gf-v3-garden-plot">{Array.from({length:12},(_,slot)=>{const placed=plots.find(p=>p.slot===slot);const item=items.find(i=>i.id===placed?.item_id);return <button key={slot} disabled={!!placed||!chosen||busy} onClick={()=>void place(slot)} className={placed?'placed':''} aria-label={`Garden space ${slot+1}${item?', '+item.name:''}`}><span>{item?.icon||'+'}</span><small>{item?.name||'Open plot'}</small></button>})}</div><div className="gf-v3-world-hint"><Info size={15}/> Select an item before tapping a plot. Purchased items remain in your garden.</div></section>:<section className="gf-v3-world-content"><div className="gf-v3-section-heading"><div><span className="gf-v3-eyebrow">SPEND GREEN CREDITS</span><h2>Garden store</h2></div><span>{items.length} items</span></div><p className="gf-v3-world-subtitle">Pick something you like, then return to your garden to place it.</p><div className="gf-v3-world-shop">{items.map(item=><button key={item.id} type="button" onClick={()=>{setChosen(item);setTab('garden')}}><span>{item.icon}</span><strong>{item.name}</strong><small>{item.price} credits</small><span className="gf-v3-world-add">Choose <ArrowRight size={13}/></span></button>)}</div>{!items.length&&<p className="gf-v3-world-subtitle">Items will appear here when the store is configured.</p>}</section>}
   <p className="gf-v3-disclaimer"><Info size={14}/> Credits are spendable rewards. Purchasing garden items does not reduce your lifetime Green Score.</p>
 </div></GreenShell>
}
