'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Award,CheckCircle2,ScanLine,Target,Trophy} from 'lucide-react';
import GreenShell from '@/app/components/GreenShell';
import {useStudent} from '@/app/lib/useStudent';
import {supabase} from '@/lib/supabaseClient';
export default function Achievements(){const {userId}=useStudent();const [count,setCount]=useState(0),[score,setScore]=useState(0);
 useEffect(()=>{if(!userId)return;let live=true;void(async()=>{const [a,w]=await Promise.all([supabase.from('gf_actions').select('id',{count:'exact',head:true}).eq('user_id',userId),supabase.from('gf_wallets').select('lifetime_points').eq('user_id',userId).maybeSingle()]);if(live){setCount(a.count||0);setScore(Number(w.data?.lifetime_points)||0)}})();return()=>{live=false}},[userId]);
 const badges=[{title:'First action',detail:'Record your first eligible recycling action',current:count,target:1,Icon:ScanLine},{title:'Building a habit',detail:'Record 5 eligible recycling actions',current:count,target:5,Icon:Target},{title:'Momentum',detail:'Earn 100 lifetime Green Score',current:score,target:100,Icon:Trophy},{title:'Impact maker',detail:'Earn 500 lifetime Green Score',current:score,target:500,Icon:Award}];
 return <GreenShell><div className="gf-screen gf-v3-page gf-v3-achievements"><Link className="gf-v3-back" href="/profile"><ArrowLeft size={17}/> Back to profile</Link><header className="gf-v3-page-heading"><span className="gf-v3-eyebrow">YOUR MILESTONES</span><h1>Achievements<span className="gf-v3-title-period">.</span></h1><p>Real progress deserves recognition.</p></header><div className="gf-v3-achievement-summary"><Award size={35}/><div><strong>{badges.filter(b=>b.current>=b.target).length} of {badges.length} unlocked</strong><p>Every eligible action brings you closer to your next milestone.</p></div></div><div className="gf-v3-badges">{badges.map(({title,detail,current,target,Icon})=>{const done=current>=target;return <article key={title} className={done?'unlocked':''}><span className="gf-v3-badge-icon"><Icon size={26}/></span><div><h2>{title} {done&&<CheckCircle2 size={17}/>}</h2><p>{detail}</p><div className="gf-v3-badge-progress"><i style={{width:`${Math.min(100,current/target*100)}%`}}/></div><small>{Math.min(current,target).toLocaleString()} / {target.toLocaleString()}</small></div></article>})}</div></div></GreenShell>}
