'use client';
import BrandAdmin from '@/app/components/BrandAdmin';
import {useCallback,useEffect,useState} from 'react';
import GreenShell from '@/app/components/GreenShell';
import {supabase} from '@/lib/supabaseClient';
import {useStudent} from '@/app/lib/useStudent';
type Bin={id:string;code:string;name:string;hostel:string;material:string;points:number;active:boolean};
type Category={slug:string;name:string;description:string;active:boolean};
export default function Admin(){
 const {userId}=useStudent();
 const [authorized,setAuthorized]=useState(false),[bins,setBins]=useState<Bin[]>([]),[categories,setCategories]=useState<Category[]>([]);
 const [code,setCode]=useState(''),[name,setName]=useState(''),[hostel,setHostel]=useState('Hall 4'),[material,setMaterial]=useState(''),[points,setPoints]=useState(10);
 const [categoryName,setCategoryName]=useState(''),[categorySlug,setCategorySlug]=useState(''),[categoryDescription,setCategoryDescription]=useState('');
 const [editing,setEditing]=useState<string|null>(null),[editingBin,setEditingBin]=useState<string|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const headers={Authorization:`Bearer ${session.access_token}`};const [a,b]=await Promise.all([fetch('/api/pilot-admin/bins',{headers}),fetch('/api/pilot-admin/categories',{headers})]);if(!a.ok||!b.ok){setError(a.status===403||b.status===403?'This account has not been appointed as an administrator.':'Could not load admin data. Apply both SQL migrations before using this page.');return;}const x=await a.json(),y=await b.json();setAuthorized(true);setBins(x.bins||[]);setCategories(y.categories||[]);},[]);
 useEffect(()=>{if(userId)void load()},[userId,load]);
 async function act(endpoint:'bins'|'categories',payload:Record<string,unknown>){setError('');setSuccess('');setBusy(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Please sign in again');const r=await fetch(`/api/pilot-admin/${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(payload)});const result=await r.json();if(!r.ok)throw Error(result.error||'Request failed');await load();setSuccess('Changes saved successfully.');return true;}catch(e){setError(e instanceof Error?e.message:'Request failed');return false;}finally{setBusy(false)}}
 async function printSticker(bin:Bin){setError('');const win=window.open('','_blank');if(!win){setError('Allow pop-ups to print stickers');return}win.document.write('<p>Preparing QR sticker…</p>');const {data:{session}}=await supabase.auth.getSession();const r=await fetch(`/api/pilot-admin/qr?code=${encodeURIComponent(bin.code)}`,{headers:{Authorization:`Bearer ${session?.access_token||''}`}});if(!r.ok){win.close();setError('Could not generate QR sticker');return}const html=await r.text();win.document.open();win.document.write(html);win.document.close();}
 const activeCategories=categories.filter(c=>c.active);
 return <GreenShell><div className="gf-admin-layout gf-screen"><header className="gf-screen-intro"><span className="gf-kicker">GREENFLARE CONTROL CENTER</span><h1>Manage the movement.</h1><p>Configure collection points, waste categories, identity and printable QR labels.</p></header><section className="gf-admin-summary"><h2>Workspace overview</h2><p className="gf-muted">Create and manage the places where people can participate.</p>
 {error&&<div className="gf-error" role="alert">{error}</div>}{success&&<p role="status" style={{color:'#047857',fontWeight:700}}>{success}</p>}
 {authorized&&<>
 <section className="gf-grid gf-section"><article className="gf-card gf-stat"><small>Registered bins</small><strong>{bins.length}</strong><span>Total collection points</span></article><article className="gf-card gf-stat"><small>Active bins</small><strong>{bins.filter(b=>b.active).length}</strong><span>Available for scanning</span></article><article className="gf-card gf-stat"><small>Waste categories</small><strong>{categories.length}</strong><span>Admin-created materials</span></article><article className="gf-card gf-stat"><small>Available categories</small><strong>{activeCategories.length}</strong><span>Visible for registration</span></article></section><section className="gf-card gf-section"><h2 className="gf-title">From setup to first scan</h2><p className="gf-muted">1. Create your material categories. &nbsp; 2. Register a designated bin. &nbsp; 3. Generate the sticker on the public HTTPS domain. &nbsp; 4. Print and attach it to the physical bin. &nbsp; 5. Test with a member account.</p></section><section className="gf-card gf-section"><h2 className="gf-title">Waste categories</h2><p className="gf-muted">Create the options that appear in the material dropdown when registering a bin. Categories can be edited and disabled without deleting their history.</p>
 <form onSubmit={async e=>{e.preventDefault();if(await act('categories',{action:'create',slug:categorySlug,name:categoryName,description:categoryDescription})){setCategoryName('');setCategorySlug('');setCategoryDescription('')}}}>
 <div className="gf-grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))'}}>
 <label className="gf-label">Category name<input required maxLength={70} className="gf-field" value={categoryName} onChange={e=>{const v=e.target.value;setCategoryName(v);setCategorySlug(v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,''))}} placeholder="Tin cans"/></label>
 <label className="gf-label">Category code<input required pattern="[a-z][a-z0-9_]{1,39}" title="2–40 lowercase letters, digits or underscores" className="gf-field" value={categorySlug} onChange={e=>setCategorySlug(e.target.value.toLowerCase())} placeholder="tin_cans"/></label>
 <label className="gf-label">Description (optional)<input maxLength={400} className="gf-field" value={categoryDescription} onChange={e=>setCategoryDescription(e.target.value)} placeholder="Aluminium and tin containers"/></label></div><button disabled={busy} className="gf-button dark">Add category</button></form>
 {categories.map(c=><div key={c.slug} className="gf-row" style={{flexWrap:'wrap',gap:12}}><div style={{flex:1,minWidth:180}}>{editing===c.slug?<form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(await act('categories',{action:'update',slug:c.slug,name:String(form.get('name')),description:String(form.get('description'))}))setEditing(null)}}><input aria-label="Category name" required className="gf-field" name="name" defaultValue={c.name} maxLength={70}/><input aria-label="Category description" className="gf-field" name="description" defaultValue={c.description} maxLength={400}/><button disabled={busy} className="gf-button dark" type="submit">Save</button> <button className="gf-button secondary" type="button" onClick={()=>setEditing(null)}>Cancel</button></form>:<><b>{c.name}</b> <small className="gf-muted">({c.slug})</small><p className="gf-muted">{c.description||'No description'} · {c.active?'Active':'Inactive'}</p></>}</div><button disabled={busy} className="gf-button secondary" onClick={()=>setEditing(editing===c.slug?null:c.slug)}>Edit</button><button disabled={busy} className="gf-button secondary" onClick={()=>void act('categories',{action:'toggle',slug:c.slug,active:!c.active})}>{c.active?'Disable':'Enable'}</button></div>)}
 </section>
 <BrandAdmin/><section className="gf-card gf-section"><h2 className="gf-title">Register a recycling bin</h2><form onSubmit={async e=>{e.preventDefault();if(await act('bins',{action:'create',code:code.toUpperCase(),name,hostel,material,points})){setCode('');setName('')}}}>
 <div className="gf-grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))'}}><label className="gf-label">Unique bin code<input required className="gf-field" value={code} onChange={e=>setCode(e.target.value)} placeholder="GF-CITY-AREA-TN-001"/></label><label className="gf-label">Bin display name<input required className="gf-field" value={name} onChange={e=>setName(e.target.value)} placeholder="Tin collection point"/></label><label className="gf-label">Collection location<input required className="gf-field" value={hostel} onChange={e=>setHostel(e.target.value)}/></label><label className="gf-label">Waste category<select required className="gf-field" value={material} onChange={e=>setMaterial(e.target.value)}><option value="">Select category</option>{activeCategories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></label><label className="gf-label">Green Score reward<input type="number" min="1" max="100" className="gf-field" value={points} onChange={e=>setPoints(Number(e.target.value))}/></label></div><button disabled={busy||!activeCategories.length} className="gf-button dark">Create bin</button></form></section>
 <section className="gf-card gf-section"><h2 className="gf-title">Registered bins ({bins.length})</h2>{bins.map(b=><div key={b.id} className="gf-row" style={{flexWrap:'wrap',gap:10}}><div style={{flex:1,minWidth:210}}><b>{b.name}</b><p className="gf-muted">{b.code} · {b.hostel} · {categories.find(c=>c.slug===b.material)?.name||b.material} · +{b.points} Green Score · {b.active?'Active':'Inactive'}</p><button className="gf-button secondary" onClick={()=>void printSticker(b)}>Print QR sticker ↗</button> <button className="gf-button secondary" onClick={()=>setEditingBin(editingBin===b.id?null:b.id)}>Edit bin</button>{editingBin===b.id&&<form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(await act('bins',{action:'update',id:b.id,name:String(form.get('name')),hostel:String(form.get('hostel')),material:String(form.get('material')),points:Number(form.get('points'))}))setEditingBin(null)}} style={{marginTop:15}}><label className="gf-label">Bin name<input className="gf-field" required name="name" defaultValue={b.name}/></label><label className="gf-label">Collection location<input className="gf-field" required name="hostel" defaultValue={b.hostel}/></label><label className="gf-label">Waste category<select name="material" className="gf-field" defaultValue={b.material}>{categories.map(c=><option disabled={!c.active&&c.slug!==b.material} value={c.slug} key={c.slug}>{c.name}</option>)}</select></label><label className="gf-label">Points<input className="gf-field" type="number" min="1" max="100" required name="points" defaultValue={b.points}/></label><button disabled={busy} className="gf-button dark">Save bin</button></form>}</div><button disabled={busy} className="gf-button secondary" onClick={()=>void act('bins',{action:'toggle',id:b.id,active:!b.active})}>{b.active?'Deactivate':'Activate'}</button></div>)}</section>
 </>}</section></div></GreenShell>;
}
