import {NextResponse} from 'next/server';
import {getAdmin} from '@/app/lib/adminServer';
const validSlug=(v:string)=>/^[a-z][a-z0-9_]{1,39}$/.test(v);
const failed=(e:unknown)=>NextResponse.json({error:e instanceof Error?e.message:'Server error'},{status:500});
export async function GET(req:Request){try{const {db,user}=await getAdmin(req);if(!user)return NextResponse.json({error:'Forbidden'},{status:403});const {data,error}=await db.from('gf_material_categories').select('slug,name,description,active').order('name');if(error)throw error;return NextResponse.json({categories:data})}catch(e){return failed(e)}}
export async function POST(req:Request){try{const {db,user}=await getAdmin(req);if(!user)return NextResponse.json({error:'Forbidden'},{status:403});const body=await req.json();const action=String(body.action||'');
if(action==='create'){const slug=String(body.slug||'').trim().toLowerCase(),name=String(body.name||'').trim(),description=String(body.description||'').trim();if(!validSlug(slug)||name.length<2||name.length>70||description.length>400)return NextResponse.json({error:'Invalid category name, code or description'},{status:400});const {error}=await db.from('gf_material_categories').insert({slug,name,description});if(error){if(error.code==='23505')return NextResponse.json({error:'Category name or code already exists'},{status:409});throw error}}
else if(action==='update'){const slug=String(body.slug||''),name=String(body.name||'').trim(),description=String(body.description||'').trim();if(!validSlug(slug)||name.length<2||name.length>70||description.length>400)return NextResponse.json({error:'Invalid category details'},{status:400});const {data,error}=await db.from('gf_material_categories').update({name,description}).eq('slug',slug).select('slug').maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:'Category not found'},{status:404})}
else if(action==='toggle'){const slug=String(body.slug||'');if(!validSlug(slug)||typeof body.active!=='boolean')return NextResponse.json({error:'Invalid request'},{status:400});if(!body.active){const {count,error}=await db.from('gf_bins').select('id',{head:true,count:'exact'}).eq('material',slug).eq('active',true);if(error)throw error;if(count)return NextResponse.json({error:`Deactivate the ${count} active bin(s) using this category first.`},{status:409})}const {data,error}=await db.from('gf_material_categories').update({active:body.active}).eq('slug',slug).select('slug').maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:'Category not found'},{status:404})}
else return NextResponse.json({error:'Unknown action'},{status:400});return NextResponse.json({ok:true});}catch(e){return failed(e)}}
